CREATE TABLE IF NOT EXISTS posts (
  id INTEGER UNSIGNED AUTO_INCREMENT NOT NULL,
  topic_id INTEGER UNSIGNED NOT NULL,
  name VARCHAR(255),
  body TEXT(255) NOT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);
